### ISSUE TITLE
Startup Error DistanceRangedMarker

### ISSUE THREAD

**Issue by colaman90** [Mark-225/BlueBridge#18]
Dear all,

we receive an startup error on Paper 1.19.2 and BlueMap 3.0:

```
[04:26:04] [Server thread/INFO]: [BlueBridgeCore] Enabling BlueBridgeCore vv1.3.1-alpha
[04:26:04] [Server thread/ERROR]: Error occurred while enabling BlueBridgeCore vv1.3.1-alpha (Is it up to date?)
java.lang.NoClassDefFoundError: de/bluecolored/bluemap/api/marker/DistanceRangedMarker
	at de.mark225.bluebridge.core.BlueBridgeCore.onEnable(BlueBridgeCore.java:39) ~[BlueBridgeCore-v1.3.1-alpha.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-130]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-130]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-130]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-130]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-130]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-130]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-130]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.bluecolored.bluemap.api.marker.DistanceRangedMarker
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
[04:26:04] [Server thread/INFO]: [BlueBridgeCore] Disabling BlueBridgeCore vv1.3.1-alpha
```

Kind regards
Cola

**Comment by Mark-225** [comment]
This is due to BlueMap 3.0 having a new API version. Supporting this new API requires a rewrite of major parts of the core module, which will probably take a while.

**Comment by Mark-225** [comment]
Release 2.1 is compatible with the newest BlueMap version
